name: 'PR from test to master'
description: 'Check if test is behind master, if so create a branch capturing the state of test and open a PR to master from it'
author: 'iFit'
inputs:
  github-api-token:
    description: 'get this from 1password'
  repository-name:
    description: 'the name of the repository this the PR will be created for'
  pr-reviewers:
    description: 'Comma seperated list of github user ids who will review the PR'
    default: ''
  pr-team-reviewers:
    description: 'Comma seperated list of github teams who will review the PR'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'